services:
  fastapi:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      PYTHONPATH: /app
      JWT_SECRET: "YOUR JWT SECRET"
      # used for migration from local database
      # DB_URL: "postgresql+asyncpg://username:password@host:port/db"
      DB_DOCKER_URL: "postgresql+asyncpg://Plantique:Plantique@postgres:5432/plantique_db"

      STRIPE_CHECKOUT_PUBLISHABLE_KEY: "YOUR STRIPE PUBLISH KEY"
      STRIPE_CHECKOUT_SECRET_KEY: "YOUR STRIPE SECRET KEY"

  react:
    build:
      context: ./Frontend/React
      dockerfile: Dockerfile
    restart: always
    environment:
      VITE_STRIPE_PUBLISH: "YOUR STRIPE PUBLISH KEY"
    ports:
      - "3000:3000"
    volumes:
      - react_static:/usr/share/nginx/html
    depends_on:
      - fastapi

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Plantique
      POSTGRES_PASSWORD: Plantique
      POSTGRES_DB: plantique_db
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - react_static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - react

volumes:
  postgres_data:
  react_static:
