"""Deleted unit_price field from cart_plant_association table

Revision ID: 77b49f7755e7
Revises: dc26b12d224c
Create Date: 2024-04-26 20:09:17.190304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77b49f7755e7"
down_revision: Union[str, None] = "dc26b12d224c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_plant_association", "unit_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_plant_association",
        sa.Column(
            "unit_price",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
