"""Altered users.id columns with foreign key to User table for Cart, Order and Profile tables

Revision ID: 94a27a06ef82
Revises: 498bf7c81881
Create Date: 2024-04-07 19:48:48.009085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94a27a06ef82"
down_revision: Union[str, None] = "498bf7c81881"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("carts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("carts_users.id_key", "carts", type_="unique")
    op.create_unique_constraint(None, "carts", ["user_id"])
    op.create_foreign_key(None, "carts", "users", ["user_id"], ["id"])
    op.drop_column("carts", "users.id")
    op.add_column("orders", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("orders_users.id_key", "orders", type_="unique")
    op.create_unique_constraint(None, "orders", ["user_id"])
    op.create_foreign_key(None, "orders", "users", ["user_id"], ["id"])
    op.drop_column("orders", "users.id")
    op.add_column("profiles", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("profiles_users.id_key", "profiles", type_="unique")
    op.create_unique_constraint(None, "profiles", ["user_id"])
    op.create_foreign_key(None, "profiles", "users", ["user_id"], ["id"])
    op.drop_column("profiles", "users.id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("users.id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "profiles", type_="foreignkey")
    op.drop_constraint(None, "profiles", type_="unique")
    op.create_unique_constraint("profiles_users.id_key", "profiles", ["users.id"])
    op.drop_column("profiles", "user_id")
    op.add_column(
        "orders",
        sa.Column("users.id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="unique")
    op.create_unique_constraint("orders_users.id_key", "orders", ["users.id"])
    op.drop_column("orders", "user_id")
    op.add_column(
        "carts", sa.Column("users.id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.drop_constraint(None, "carts", type_="unique")
    op.create_unique_constraint("carts_users.id_key", "carts", ["users.id"])
    op.drop_column("carts", "user_id")
    # ### end Alembic commands ###
