"""Fixed unique User ID field

Revision ID: c74a9b13738d
Revises: 3f509026c54c
Create Date: 2024-05-17 15:11:06.975814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c74a9b13738d"
down_revision: Union[str, None] = "3f509026c54c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_user_id_key", "orders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("orders_user_id_key", "orders", ["user_id"])
    # ### end Alembic commands ###
