"""Added many-to-one relation from categories to collections

Revision ID: ed86cd978786
Revises: 95156a7b4dc9
Create Date: 2024-04-07 18:43:27.498320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed86cd978786"
down_revision: Union[str, None] = "95156a7b4dc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("collection_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "categories", "collections", ["collection_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "collection_id")
    # ### end Alembic commands ###
