"""Create carts table

Revision ID: ce679ccf6933
Revises: 433f4da1cfed
Create Date: 2024-04-05 23:31:27.101470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce679ccf6933"
down_revision: Union[str, None] = "433f4da1cfed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("users.id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("users.id"),
    )
    op.add_column("users", sa.Column("cart_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "carts", ["cart_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "cart_id")
    op.drop_table("carts")
    # ### end Alembic commands ###
