"""Added unique constraint to cart plant association

Revision ID: 2fa5467baf01
Revises: e610d270025a
Create Date: 2024-04-07 19:25:14.222544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fa5467baf01"
down_revision: Union[str, None] = "e610d270025a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_unique_cart_plant", "cart_plant_association", ["cart_id", "plant_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_unique_cart_plant", "cart_plant_association", type_="unique")
    # ### end Alembic commands ###
