"""Deleted Cascade ondelete constraint from categories table

Revision ID: 2de48d1141e2
Revises: 7259c44bb239
Create Date: 2024-04-11 17:53:37.878625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2de48d1141e2"
down_revision: Union[str, None] = "7259c44bb239"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("categories_collection_id_fkey", "categories", type_="foreignkey")
    op.create_foreign_key(None, "categories", "collections", ["collection_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.create_foreign_key(
        "categories_collection_id_fkey",
        "categories",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
