"""Created cascade deletion for user relations

Revision ID: 7259c44bb239
Revises: d9648beeae6b
Create Date: 2024-04-07 23:36:49.920359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7259c44bb239"
down_revision: Union[str, None] = "d9648beeae6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("carts_user_id_fkey", "carts", type_="foreignkey")
    op.create_foreign_key(None, "carts", "users", ["user_id"], ["id"])
    op.drop_constraint("orders_user_id_fkey", "orders", type_="foreignkey")
    op.create_foreign_key(None, "orders", "users", ["user_id"], ["id"])
    op.drop_constraint("profiles_user_id_fkey", "profiles", type_="foreignkey")
    op.create_foreign_key(None, "profiles", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="foreignkey")
    op.create_foreign_key(
        "profiles_user_id_fkey",
        "profiles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        "orders_user_id_fkey", "orders", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.create_foreign_key(
        "carts_user_id_fkey", "carts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
