"""Deleted foreign key pointing to Cart table from User table

Revision ID: 4a21baa68558
Revises: 94a27a06ef82
Create Date: 2024-04-07 19:54:58.006336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a21baa68558"
down_revision: Union[str, None] = "94a27a06ef82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_cart_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "cart_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("cart_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key("users_cart_id_fkey", "users", "carts", ["cart_id"], ["id"])
    # ### end Alembic commands ###
